<img src='https://data.actris.eu/static/img/actris-dc-logo.png' width=400 align=right>

# Search with ACTRIS Metadata Rest API

This notebook shows how to search for and discover atmospheric datasets in the ACTRIS data catalogue using the DVAS Python client. It is aimed at scientists who want to find data programmatically, for example to automate data retrieval, search across many datasets, or build reproducible workflows.

You will learn how to:
- Search for datasets by variable, country, and time period
- Explore the metadata returned for each dataset
- Get download links for the data files

### The ACTRIS DVAS API client

ACTRIS metadata is accessed through the **DVAS** (Data Discovery, Virtual Access and Services) platform. The `dvas-api-client` Python package provides a simple way to search the catalogue without writing raw HTTP requests.

Install the client with:
```
pip install dvas-api-client
```

Useful links:
- DVAS API client documentation: https://pypi.org/project/dvas-api-client/
- Full API reference (Swagger): https://prod-actris-md.nilu.no/swagger-ui/index.html
- ACTRIS vocabulary (variable names, matrices, etc.): https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/

### Import libraries

In [4]:
import pandas as pd
from dvas.client import BoolQuery, QueryField, SortType, PROD_API, search

## Exploring the metadata structure

Before running targeted searches, it helps to look at what a metadata record actually contains. The cell below fetches a small sample so you can inspect the structure.

Each result is a Python dictionary with sections like `identification`, `variables`, and `distribution_information`.

In [25]:
# Fetch a small sample of In-Situ (EBAS) datasets to explore the metadata structure.
# Omitting .sort() keeps pagination disabled, so only one page of results (size=10) is returned.
query = (
    BoolQuery(size=10)
    .must(QueryField.DATASET_REPOSITORY_ID, "In-Situ")
)

docs = list(search(PROD_API, query))
print(f"Fetched {len(docs)} datasets")

Fetched 10 datasets

In [26]:
# Show the full metadata record for the first dataset.
# The top-level keys show the main sections: identification, variables, distribution_information, etc.
docs[0]

{'dataset_metadata': {'repository': {'repository_id': 'In-Situ'},
  'time_file_created': '2026-07-13T08:07:21.13Z',
  'time_metadata_created': '2026-07-13T08:12:15.515Z',
  'time_content_revised': '2026-07-13T08:07:21.13Z'},
 'identification': {'identifier': {'pid': 'https://doi.org/10.48597/3TFV-VEU5',
   'pid_type': 'DOI'},
  'title': "Aerosol_absorption_coefficient at Observatoire Perenne de l'Environnement",
  'abstract': "Aerosol_absorption_coefficient at Observatoire Perenne de l'Environnement. These measurements are gathered as a part of the following projects ACTRIS, GAW-WDCA and they are stored in the EBAS database (http://ebas.nilu.no/). Parameters measured are: ['aerosol_absorption_coefficient in pm25']",
  'roles': [{'role_code': ['pointOfContact'],
    'person': {'first_name': 'Nicolas', 'last_name': 'Pascal'}},
   {'role_code': ['principalInvestigator', 'originator'],
    'person': {'first_name': 'Paolo',
     'last_name': 'Villani',
     'affiliation': {'name': 'Observatoire de Physique du Globe de Clermont-Ferrand'}}},
   {'role_code': ['principalInvestigator', 'originator'],
    'person': {'first_name': 'Sebastien',
     'last_name': 'Conil',
     'affiliation': {'name': "Observatoire Perenne de l'Environnement"}}}],
  'organisations': [{'role_code': 'funding organisation',
    'organisation': {'name': ' (Andra)', 'country_code': 'FR'}},
   {'role_code': 'data provider',
    'organisation': {'name': ' (Andra)', 'country_code': 'FR'}}]},
 'usage_information': {'data_licence': 'CC-BY-4.0',
  'metadata_licence': 'CC0-1.0',
  'citation': "Villani, P., Conil, S., ACTRIS, GAW-WDCA, 2026, Aerosol_absorption_coefficient at Observatoire Perenne de l'Environnement, data hosted by EBAS at NILU, DOI: https://doi.org/10.48597/3TFV-VEU5",
  'acknowledgement': 'Data used in this <study/report/figure/etc.> were accessed from EBAS (https://ebas.nilu.no) hosted by NILU. Specifically, the use included data affiliated with the frameworks: ACTRIS, GAW-WDCA. For using this data for any kind of publications, you must contact the data originator(s), in terms of acknowledgment'},
 'product_type': 'observation',
 'facility': {'identifier': '2wep',
  'name': "Observatoire Perenne de l'Environnement",
  'facility_type': ['observation platform, fixed'],
  'location': {'type': 'Point',
   'coordinates': [5.505556, 48.56222, 392.0],
   'bbox': []},
  'country_code': 'FR',
  'wmo_region': 'Europe',
  'uri': 'https://data.actris.eu/facility/2wep',
  'identifier_type': 'other PID',
  'active': False,
  'actris_national_facility': 'not labelled',
  'gawid_uri': 'OPE',
  'extra_metadata': {'insitu': {'ebas_station_code': 'FR0022R',
    'ebas_station_name': "Observatoire Perenne de l'Environnement",
    'ebas_station_lat': 48.562222222222225,
    'ebas_station_lon': 5.5055555555555555,
    'ebas_station_alt': 392.0,
    'ebas_country_code': 'FR'}}},
 'spatial_extent': {'type': 'MultiPoint',
  'coordinates': [[5.505, 48.562, 392.0],
   [5.5055555555555555, 48.562222222222225, 392.0]]},
 'temporal_extent': {'time_period_begin': '2023-01-01T00:00:00Z',
  'time_period_end': '2026-01-01T00:00:00Z'},
 'variables': [{'variable_name': 'aerosol particle light absorption coefficient',
   'variable_property_of_interest': 'light absorption coefficient',
   'object_of_interest': 'particle phase',
   'variable_matrix': 'PM2.5',
   'timeliness': 'scheduled',
   'instrument': [{'validtime_start': '2023-01-01T00:00:00Z',
     'validtime_end': '2026-01-01T00:00:00Z',
     'instrument_type': 'filter absorption photometer',
     'instrument_name': 'Magee_AE33_S05-00510_OPE_pm25',
     'extra_metadata': {'insitu': {'ebas_instrument_ref': 'FR11L_Magee_AE33_S05-00510_OPE_pm25',
       'ebas_instrument_type': 'filter_absorption_photometer',
       'ebas_instrument_manufacturer': 'Magee',
       'ebas_instrument_model': 'AE33',
       'ebas_instrument_serialno': 'AE33-S05-00510'}}}],
   'framework': [{'validtime_start': '2023-01-01T00:00:00Z',
     'validtime_end': '2024-01-01T00:00:00Z',
     'framework': 'ACTRIS',
     'extra_metadata': {'insitu': {'ebas_framework': 'ACTRIS'}}},
    {'validtime_start': '2023-01-01T00:00:00Z',
     'validtime_end': '2024-01-01T00:00:00Z',
     'framework': 'GAW-WDCA',
     'extra_metadata': {'insitu': {'ebas_framework': 'GAW-WDCA'}}}],
   'method': {'title': 'FR07L_AE33manual',
    'extra_metadata': {'insitu': {'ebas_method_ref': 'FR07L_AE33manual',
      'ebas_standard_method': 'Single-angle_Correction=Drinovec2015'}}},
   'temporal_resolution': 'PT1H',
   'extra_metadata': {'insitu': {'ebas_matrix': 'pm25',
     'ebas_component_name': 'aerosol_absorption_coefficient',
     'ebas_unit': '1/Mm',
     'nc_varname': 'v_aerosol_absorption_coefficient_amean'}}}],
 'distribution_information': [{'data_format': 'netCDF download',
   'dataset_url': 'https://thredds.nilu.no/thredds/fileServer/ebas_doi/3T/FV/VE/3TFV-VEU5.nc',
   'protocol': 'HTTP',
   'access_restriction': {'restricted': False},
   'transfersize': {'size': 7692690.0, 'unit': 'B'}},
  {'data_format': 'OPeNDAP',
   'dataset_url': 'https://thredds.nilu.no/thredds/dodsC/ebas_doi/3T/FV/VE/3TFV-VEU5.nc',
   'protocol': 'OPeNDAP',
   'access_restriction': {'restricted': False}}]}

In [27]:
# The 'identification' section holds the dataset title, persistent identifier (PID/DOI), and contact info.
# Here we extract it from all sampled datasets and display it as a table.
id_list = [doc['identification'] for doc in docs]
df_identification = pd.DataFrame.from_records(id_list)

df_identification.iloc[0]  # show identification fields for the first dataset

identifier       {'pid': 'https://doi.org/10.48597/3TFV-VEU5', ...
title            Aerosol_absorption_coefficient at Observatoire...
abstract         Aerosol_absorption_coefficient at Observatoire...
roles            [{'role_code': ['pointOfContact'], 'person': {...
organisations    [{'role_code': 'funding organisation', 'organi...
Name: 0, dtype: object

In [ ]:
# The 'roles' field lists the people and organisations responsible for the dataset (e.g. principal investigator).
df_identification.iloc[0]['roles']

[{'role_code': ['pointOfContact'],
  'person': {'first_name': 'Nicolas', 'last_name': 'Pascal'}},
 {'role_code': ['principalInvestigator', 'originator'],
  'person': {'first_name': 'Paolo',
   'last_name': 'Villani',
   'affiliation': {'name': 'Observatoire de Physique du Globe de Clermont-Ferrand'}}},
 {'role_code': ['principalInvestigator', 'originator'],
  'person': {'first_name': 'Sebastien',
   'last_name': 'Conil',
   'affiliation': {'name': "Observatoire Perenne de l'Environnement"}}}]

In [31]:
# The 'variables' section describes what was measured: variable name, matrix (e.g. gas phase), unit, instrument, etc.
# Each dataset can have multiple variables, so we flatten them all into one table.
variables_list = [v for doc in docs for v in doc.get('variables', [])]
df_variables = pd.DataFrame.from_records(variables_list)

df_variables

,variable_name,variable_property_of_interest,object_of_interest,variable_matrix,timeliness,instrument,framework,method,temporal_resolution,extra_metadata,variable_constraints
0,aerosol particle light absorption coefficient,light absorption coefficient,particle phase,PM2.5,scheduled,"[{'validtime_start': '2023-01-01T00:00:00Z', '...","[{'validtime_start': '2023-01-01T00:00:00Z', '...","{'title': 'FR07L_AE33manual', 'extra_metadata'...",PT1H,"{'insitu': {'ebas_matrix': 'pm25', 'ebas_compo...",NaN
1,aerosol particle number concentration,number concentration,particle phase,aerosol particle phase,scheduled,"[{'validtime_start': '2025-01-01T16:00:00Z', '...","[{'validtime_start': '2025-01-01T16:00:00Z', '...","{'title': 'DE62L_CPC25', 'extra_metadata': {'i...",PT1H,"{'insitu': {'ebas_matrix': 'aerosol', 'ebas_co...",NaN
2,aerosol particle light hemispheric backscatter...,light hemispheric backscatter coefficient,particle phase,aerosol particle phase,scheduled,"[{'validtime_start': '2019-01-01T00:00:00Z', '...","[{'validtime_start': '2019-01-01T00:00:00Z', '...","{'title': 'FR11L_Ecotech_Aurora3000_OPE', 'ext...",PT1H,"{'insitu': {'ebas_matrix': 'aerosol', 'ebas_co...",NaN
3,aerosol particle light scattering coefficient,light scattering coefficient,particle phase,aerosol particle phase,scheduled,"[{'validtime_start': '2019-01-01T00:00:00Z', '...","[{'validtime_start': '2019-01-01T00:00:00Z', '...","{'title': 'FR11L_Ecotech_Aurora3000_OPE', 'ext...",PT1H,"{'insitu': {'ebas_matrix': 'aerosol', 'ebas_co...",NaN
4,nitrogen dioxide amount fraction,amount fraction,nitrogen dioxide,gas phase,scheduled,"[{'validtime_start': '2023-01-01T00:00:00Z', '...","[{'validtime_start': '2023-01-01T00:00:00Z', '...",{'title': 'GB03L_AUC_T500U_DE20L_NOx_corr_offs...,PT1H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
5,nitrogen dioxide mass concentration,mass concentration,nitrogen dioxide,gas phase,scheduled,"[{'validtime_start': '2023-01-01T00:00:00Z', '...","[{'validtime_start': '2023-01-01T00:00:00Z', '...",{'title': 'GB03L_AUC_T500U_DE20L_NOx_corr_offs...,PT1H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",[{'constraint': 'expressed as nitrogen'}]
6,2-methylbutane mass concentration,mass concentration,2-methylbutane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
7,2-methylbutane amount fraction,amount fraction,2-methylbutane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
8,2-methyl-propane mass concentration,mass concentration,2-methyl-propane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
9,2-methyl-propane amount fraction,amount fraction,2-methyl-propane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
10,benzene mass concentration,mass concentration,benzene,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
11,benzene amount fraction,amount fraction,benzene,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
12,ethane mass concentration,mass concentration,ethane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
13,ethane amount fraction,amount fraction,ethane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
14,ethene amount fraction,amount fraction,ethene,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
15,ethyne amount fraction,amount fraction,ethyne,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
16,n-butane mass concentration,mass concentration,n-butane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
17,n-butane amount fraction,amount fraction,n-butane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
18,n-pentane mass concentration,mass concentration,n-pentane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
19,n-pentane amount fraction,amount fraction,n-pentane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
20,propane mass concentration,mass concentration,propane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
21,propane amount fraction,amount fraction,propane,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
22,toluene mass concentration,mass concentration,toluene,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
23,toluene amount fraction,amount fraction,toluene,gas phase,scheduled,"[{'validtime_start': '2024-01-01T00:06:00Z', '...","[{'validtime_start': '2024-01-01T00:06:00Z', '...","{'title': 'IT10L_AGAGE', 'extra_metadata': {'i...",PT2H,"{'insitu': {'ebas_matrix': 'air', 'ebas_compon...",NaN
24,aerosol particle light hemispheric backscatter...,light hemispheric backscatter coefficient,particle phase,PM10,scheduled,"[{'validtime_start': '2004-01-01T00:00:00Z', '...","[{'validtime_start': '2004-01-01T00:00:00Z', '...","{'title': 'US06L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm10', 'ebas_compo...",NaN
25,aerosol particle light scattering coefficient,light scattering coefficient,particle phase,PM10,scheduled,"[{'validtime_start': '2004-01-01T00:00:00Z', '...","[{'validtime_start': '2004-01-01T00:00:00Z', '...","{'title': 'US06L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm10', 'ebas_compo...",NaN
26,aerosol particle light hemispheric backscatter...,light hemispheric backscatter coefficient,particle phase,PM1,scheduled,"[{'validtime_start': '2004-01-01T00:00:00Z', '...","[{'validtime_start': '2004-01-01T00:00:00Z', '...","{'title': 'US06L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm1', 'ebas_compon...",NaN
27,aerosol particle light scattering coefficient,light scattering coefficient,particle phase,PM1,scheduled,"[{'validtime_start': '2004-01-01T00:00:00Z', '...","[{'validtime_start': '2004-01-01T00:00:00Z', '...","{'title': 'US06L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm1', 'ebas_compon...",NaN
28,aerosol particle light hemispheric backscatter...,light hemispheric backscatter coefficient,particle phase,PM10,scheduled,"[{'validtime_start': '2004-01-01T00:00:00Z', '...","[{'validtime_start': '2004-01-01T00:00:00Z', '...","{'title': 'CA01L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm10', 'ebas_compo...",NaN
29,aerosol particle light scattering coefficient,light scattering coefficient,particle phase,PM10,scheduled,"[{'validtime_start': '2004-01-01T00:00:00Z', '...","[{'validtime_start': '2004-01-01T00:00:00Z', '...","{'title': 'CA01L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm10', 'ebas_compo...",NaN
30,aerosol particle light hemispheric backscatter...,light hemispheric backscatter coefficient,particle phase,PM1,scheduled,"[{'validtime_start': '2005-01-01T00:00:00Z', '...","[{'validtime_start': '2005-01-01T00:00:00Z', '...","{'title': 'CA01L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm1', 'ebas_compon...",NaN
31,aerosol particle light scattering coefficient,light scattering coefficient,particle phase,PM1,scheduled,"[{'validtime_start': '2005-01-01T00:00:00Z', '...","[{'validtime_start': '2005-01-01T00:00:00Z', '...","{'title': 'CA01L_scat_coef', 'extra_metadata':...",PT1H,"{'insitu': {'ebas_matrix': 'pm1', 'ebas_compon...",NaN
32,aerosol particle light scattering coefficient,light scattering coefficient,particle phase,PM10,scheduled,"[{'validtime_start': '2013-01-01T00:00:00Z', '...","[{'validtime_start': '2013-01-01T00:00:00Z', '...","{'title': 'FR11L_Ecotech_Aurora3000_OPE', 'ext...",PT1H,"{'insitu': {'ebas_matrix': 'pm10', 'ebas_compo...",NaN

In [32]:
# The 'distribution_information' section lists how to access the data.
# Typically there are two entries per dataset: a direct netCDF download (HTTP) and an OPeNDAP streaming link.
dist_list = [
    {"pid": doc["identification"]["identifier"]["pid"], **entry}
    for doc in docs
    for entry in doc.get("distribution_information", [])
]
df_distribution = pd.DataFrame.from_records(dist_list)

# Show both access options for the first dataset
first_pid = df_distribution["pid"].iloc[0]
df_distribution[df_distribution["pid"] == first_pid]

,pid,data_format,dataset_url,protocol,access_restriction,transfersize
0,https://doi.org/10.48597/3TFV-VEU5,netCDF download,https://thredds.nilu.no/thredds/fileServer/eba...,HTTP,{'restricted': False},"{'size': 7692690.0, 'unit': 'B'}"
1,https://doi.org/10.48597/3TFV-VEU5,OPeNDAP,https://thredds.nilu.no/thredds/dodsC/ebas_doi...,OPeNDAP,{'restricted': False},NaN

## Searching for specific datasets

Use `BoolQuery` to filter the catalogue by variable name, country, instrument type, time period, and more. The client automatically retrieves all matching pages — just add `.sort()` to enable pagination.

Variable names and other controlled vocabulary terms can be found at: https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/

### Search by variable name

The most common starting point: find all datasets that contain a specific measured variable.

In [40]:
# Search for all In-Situ datasets that include ozone amount fraction measurements.
# Adding .sort() enables automatic pagination so all matching datasets are returned.
query = (
    BoolQuery()
    .must(QueryField.DATASET_REPOSITORY_ID, "In-Situ")
    .must(QueryField.VARIABLE_NAME, "ozone amount fraction")
    .sort([(QueryField.IDENTIFICATION_PID, SortType.ASC)])
)

docs_ozone = list(search(PROD_API, query))
print(f"Found {len(docs_ozone)} ozone amount fraction datasets")

Found 449 ozone amount fraction datasets

In [41]:
# Build a clean summary table of the search results.
# For each dataset: title, persistent identifier (PID/DOI), measured variables, and direct download URL.
rows = []
for doc in docs_ozone:
    ident = doc.get("identification", {})
    pid = ident.get("identifier", {}).get("pid", "")
    title = ident.get("title", "")
    var_names = ", ".join(v.get("variable_name", "") for v in doc.get("variables", []))
    download_url = next(
        (d["dataset_url"] for d in doc.get("distribution_information", []) if d.get("protocol") == "HTTP"),
        ""
    )
    rows.append({"title": title, "pid": pid, "variables": var_names, "download_url": download_url})

df_summary = pd.DataFrame(rows)
df_summary

,title,pid,variables,download_url
0,Ozone at Kårvatn,https://doi.org/10.48597/24HS-WKVA,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
1,Ozone at Ryori,https://doi.org/10.48597/276E-JRBR,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
2,Ozone at Kollumerwaard,https://doi.org/10.48597/27Q5-93PF,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
3,Ozone at South Pole,https://doi.org/10.48597/29AD-VCRJ,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
4,Ozone at Sandve,https://doi.org/10.48597/2B95-SF2E,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
...,...,...,...,...
444,Ozone at Gosan,https://doi.org/10.48597/ZSEJ-E9PV,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
445,Ozone at Yonaguni,https://doi.org/10.48597/ZUGN-R3GY,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
446,Ozone at Rigi,https://doi.org/10.48597/ZX2K-6G7Z,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
447,Ozone at Ryori,https://doi.org/10.48597/ZXJP-3JPD,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...
448,Ozone at Topolniky,https://doi.org/10.48597/ZYZS-QEB5,"ozone amount fraction, ozone mass concentration",https://thredds.nilu.no/thredds/fileServer/eba...

### Combining multiple filters: country and time range

You can add as many filters as you like. This example finds ozone datasets from Norwegian stations that cover any part of the period 2020–2024.

In [42]:
# Ozone datasets from Norway with temporal coverage overlapping 2020-2024.
# filter_range checks that the dataset's time extent overlaps the requested period.
query = (
    BoolQuery()
    .must(QueryField.DATASET_REPOSITORY_ID, "In-Situ")
    .must(QueryField.VARIABLE_NAME, "ozone amount fraction")
    .must(QueryField.FACILITY_COUNTRY_CODE, "NO")
    .filter_range(QueryField.TEMPORAL_EXTENT_BEGIN, lte="2024-01-01T00:00:00.000Z")
    .filter_range(QueryField.TEMPORAL_EXTENT_END, gte="2020-01-01T00:00:00.000Z")
    .sort([(QueryField.IDENTIFICATION_PID, SortType.ASC)])
)

docs_no_ozone = list(search(PROD_API, query))
print(f"Found {len(docs_no_ozone)} ozone datasets from Norway covering 2020–2024")

Found 10 ozone datasets from Norway covering 2020–2024

### Search by instrument type

You can also filter by the type of instrument used to collect the data. This example finds all lidar remote-sensing datasets from Switzerland.

In [43]:
# Search for all lidar datasets from Switzerland
query = (
    BoolQuery()
    .must(QueryField.VARIABLE_INSTRUMENT_TYPE, "lidar")
    .must(QueryField.FACILITY_COUNTRY_CODE, "CH")
    .sort([(QueryField.IDENTIFICATION_PID, SortType.ASC)])
)

docs_lidar = list(search(PROD_API, query))
print(f"Found {len(docs_lidar)} lidar datasets from Switzerland")

Found 418 lidar datasets from Switzerland

## Further resources

- **ACTRIS Data Portal** (browser-based search): https://data.actris.eu
- **Full API reference** (all available endpoints and filters): https://prod-actris-md.nilu.no/swagger-ui/index.html
- **DVAS API client** (all available `QueryField` options): https://pypi.org/project/dvas-api-client/
- **ACTRIS vocabulary** (variable names, matrices, units): https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/